sudo: required
dist: trusty
language: go
go:
  - "1.11.x"

services:
  - docker

before_install:
  - docker pull skycoin/skycoin:develop
  - mkdir /tmp/skydata
  - wget https://github.com/skycoin/skycoin/blob/develop/src/api/integration/testdata/blockchain-180.db -O /tmp/skydata/blockchain-180.db
  - docker run --detach --rm --name skycoin-blockchain-180 -v /tmp/skydata:/tmp/skydata -v /tmp/skycoin-data:/data/.skycoin -v /tmp/skycoin-wallet:/wallet -p 6000:6000 -p 6420:6420 skycoin/skycoin:develop -db-path /tmp/skydata/blockchain-180.db -db-read-only=true -disable-networking=false -download-peerlist=false -launch-browser=false -enable-all-api-sets=true
  - sleep 5

matrix:
  include:
    - os: linux
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=30s
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=30s

install:
  - if [[ ! -d $GOPATH/src/github.com/simelo/rextporter ]]; then mkdir -p $GOPATH/src/github.com/simelo; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/simelo/rextporter; fi
  - cd $GOPATH/src/github.com/simelo/rextporter
  - go get -t ./...
  - go get github.com/vektra/mockery/.../
  - make install-linters


script:
  - make lint
  - make test-386
  - make test-amd64

after_script:
  - docker images
  - docker container stop skycoin-blockchain-180
  - docker images

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
